language: php
php:
  - 5.5
  - 5.4
  - hhvm
env: # important!
matrix:
  fast_finish: true
  include:
  - php: 5.5
    env: PASS=TRUE
  allow_failures:
  - php: 5.4
    env: PASS=FALSE
script: phpunit Test.php
# https://docs.travis-ci.com/user/customizing-the-build/
