language: php
php:
  - 5.5
  - 5.4
  - 7.0
  - 7.1
  - hhvm
env: # important!
matrix:
  fast_finish: true
  include:
  - php: 7.0
    env: KEY=VALUE
  allow_failures:
  - php: 7.0
    env: KEY=VALUE
script: phpunit Test.php
# https://docs.travis-ci.com/user/customizing-the-build/
